# SPDX-FileCopyrightText: 2020 Volker Krause <vkrause@kde.org>
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/android.yml
      - /gitlab-templates/windows.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/android-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/windows-qt6.yml
      # TODO waiting for a Qt6 Flatpak runtime
      # - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-android-qt6-apks.yml

# Manual job for building a fully static cli binaries
static-tools:
  stage: deploy
  image: centos:centos7
  tags:
    - Linux
  when: manual
  script:
    - export BUILD_ROOT=/builds
    - export STAGING_ROOT=/builds/staging
    - scripts/setup-centos.sh
    - source /opt/rh/rh-git227/enable
    - source /opt/rh/devtoolset-11/enable
    - scripts/build-openssl.sh
    - scripts/build-static-qt.sh
    - scripts/build-cmake-modules.sh
    - strip build/bin/osm-download-data
  artifacts:
    expire_in: 1 week
    when: on_success
    paths:
     - build/bin/osm-download-data
