# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'libraries/kpublictransport': "@same"
    'libraries/kopeninghours': "@same"

- 'on': ['Android']
  'require':
    'frameworks/kirigami': '@stable'

Options:
  cmake-options: "-DBUILD_STANDALONE_APP=ON"
