# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'libraries/kpublictransport': "@same"
    'libraries/kopeninghours': "@same"
    'libraries/kirigami-addons': "@same"

- 'on': ['Android']
  'require':
    'frameworks/kirigami': '@latest-kf6'

- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/kservice': '@latest-kf6'

Options:
  cmake-options: "-DBUILD_STANDALONE_APP=ON"
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
